name: lwnutrition
favicon: null
layout_spectrum: 0.28324
typography_spectrum: 0.68529
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#414141'
    - '#00c900'
    - '#009ade'
    - '#000000'
    - '#808080'
  brandStrength: 0.0625
  lightness: 0.9375
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
