name: lwnutrition
favicon: null
layout_spectrum: 0.7072801990434527
typography_spectrum: 0.18432614183984697
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.11052564345300198
  lightness: 0.5725702326744795
  saturation: 0.3382388483732939
  rhythmicContrast: 0.5691568851470947
purpose: []
